apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-controller-manager
  labels:
    tier: controlplane
    k8s-app: kube-controller-manager
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      {{- if eq (int .Values.replicas) 1 }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
  selector:
    matchLabels:
      tier: controlplane
      k8s-app: kube-controller-manager
  template:
    metadata:
      labels:
        tier: controlplane
        k8s-app: kube-controller-manager
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
        # Automatically rolls update when config changes
        checksum/config: {{ include (print $.Template.BasePath "/kube-apiserver-load-balancer-config-map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/kube-controller-manager/secret.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          {{- if eq (int .Values.replicas) 1 }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: k8s-app
                  operator: In
                  values:
                  - kube-controller-manager
              topologyKey: kubernetes.io/hostname
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - controlplane
              - key: k8s-app
                operator: In
                values:
                - kube-controller-manager
            topologyKey: kubernetes.io/hostname
          {{- end }}
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: kube-controller-manager
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-controller-manager
        image: {{ .Values.kubeControllerManager.image | default (printf "k8s.gcr.io/hyperkube:v%s" .Chart.AppVersion) }}
        command:
        - ./hyperkube
        - kube-controller-manager
        - --use-service-account-credentials
        - --cluster-signing-cert-file=/etc/kubernetes/pki/client-ca-file
        - --cluster-signing-key-file=/etc/kubernetes/secrets/ca.key
        - --service-account-private-key-file=/etc/kubernetes/secrets/service-account.key
        - --root-ca-file=/etc/kubernetes/secrets/root.crt
        - --kubeconfig=/etc/kubernetes/kubeconfig
        - --authentication-kubeconfig=/etc/kubernetes/kubeconfig
        - --authorization-kubeconfig=/etc/kubernetes/kubeconfig
        - --requestheader-client-ca-file=/etc/kubernetes/pki/requestheader-client-ca-file
        - --client-ca-file=/etc/kubernetes/pki/client-ca-file
        - --flex-volume-plugin-dir={{ .Values.flexVolumePluginDir }}
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 10257
          initialDelaySeconds: 15
          timeoutSeconds: 15
        volumeMounts:
        - name: kube-controller-manager
          mountPath: /etc/kubernetes
          readOnly: true
        - name: secrets
          mountPath: /etc/kubernetes/secrets
          readOnly: true
        - name: extension-apiserver-authentication
          mountPath: /etc/kubernetes/pki
          readOnly: true
        resources:
          requests:
            memory: 80Mi
      - name: kube-apiserver-load-balancer
        image: haproxy:2.1.4-alpine
        volumeMounts:
        - name: kube-apiserver-load-balancer
          mountPath: /usr/local/etc/haproxy
          readOnly: true
        ports:
        - name: metrics
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 15
      volumes:
      - name: secrets
        secret:
          secretName: kube-controller-manager
      - name: kube-controller-manager
        configMap:
          name: kube-controller-manager
      - name: kube-apiserver-load-balancer
        configMap:
          name: kube-apiserver-load-balancer
      - name: extension-apiserver-authentication
        configMap:
          name: extension-apiserver-authentication
      dnsPolicy: Default # Don't use cluster DNS.
