apiVersion: v1
kind: Secret
metadata:
  name: kube-controller-manager
type: Opaque
data:
  service-account.key: {{ required "serviceAccountPrivateKey can't be empty!" .Values.serviceAccountPrivateKey | b64enc }}
  ca.key: {{ required "kubernetesCAKey can't be empty" .Values.kubernetesCAKey | b64enc }}
  root.crt: {{ printf "%s%s" (required "rootCACertificate can't be empty" .Values.rootCACertificate) (required "kubernetesCACertificate can't be empty" .Values.kubernetesCACertificate) | b64enc }}
