apiVersion: v1
kind: Secret
metadata:
  name: kube-controller-manager
type: Opaque
data:
  service-account.key: {{.Values.serviceAccountPrivateKey | b64enc}}
  ca.crt: {{.Values.kubernetesCACertificate | b64enc}}
  ca.key: {{.Values.kubernetesCAKey | b64enc}}
  root.crt: {{ printf "%s%s" .Values.rootCACertificate .Values.kubernetesCACertificate | b64enc }}
