apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  type: NodePort
  selector:
    k8s-app: kube-apiserver
  ports:
    - protocol: TCP
      port: 6443
      nodePort: 30443
