# If only one replica of control plane pods is requested, make sure only one pod at a time is being restarted
{{ if eq .Values.replicas 1.0 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: controlplane
spec:
  minAvailable: 2
  selector:
    matchLabels:
      pdb: controlplane
{{ end }}
