{{- if not (eq .Values.replicas 1.0) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kube-apiserver
spec:
  minAvailable: 1
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: kube-apiserver
{{- end }}
