apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
  namespace: kube-system
type: Opaque
data:
  apiserver.key: {{.Values.KubernetesAPIServerKey | b64enc}}
  apiserver.crt: {{.Values.KubernetesAPIServerCertificate | b64enc}}
  service-account.crt: {{.Values.ServiceAccountPublicKey | b64enc}}
  ca.crt: {{.Values.KubernetesCACertificate | b64enc}}
