apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy
data:
  kube-proxy.yaml: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: iptables
    clientConnection:
      kubeconfig: /etc/kubernetes/kubeconfig
    metricsBindAddress: HOST_IP
    healthzBindAddress: HOST_IP
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: local
      cluster:
        server: https://127.0.0.1:7443
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: service-account
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-apiserver-load-balancer-host
data:
  haproxy.cfg: |
    defaults
      # Do TLS passthrough
      mode tcp
      # Required values for both frontend and backend
      timeout connect 5000ms
      timeout client 50000ms
      timeout server 50000ms

    frontend kube-apiserver
      bind 127.0.0.1:7443
      default_backend kube-apiserver

    backend kube-apiserver
      {{- range $index, $server := .Values.apiServers }}
      server {{ $index }} {{ $server }} check
      {{- end }}

    frontend stats
      bind HOST_IP:38080
      mode http
      option http-use-htx
      http-request use-service prometheus-exporter if { path /metrics }
      stats enable
      stats uri /stats
      stats refresh 10s
