apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy
  namespace: kube-system
data:
  kube-proxy.yaml: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: iptables
    # That is not right for most setups
    #clusterCIDR: 10.1.0.0/24
    clientConnection:
      kubeconfig: /etc/kubernetes/kubeconfig
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: local
      cluster:
        server: https://localhost:6443
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: service-account
