apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-proxy
data:
  kube-proxy.yaml: |
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: ipvs
    ipvs:
      scheduler: rr
    clientConnection:
      kubeconfig: /etc/kubernetes/kubeconfig
    clusterCIDR: {{ required "podsCIDR must be specified!" .Values.podsCIDR }}
    metricsBindAddress: HOST_IP
    healthzBindAddress: HOST_IP
    hostnameOverride: NODE_NAME
  kubeconfig: |
    apiVersion: v1
    clusters:
    - name: local
      cluster:
        server: https://127.0.0.1:7443
        certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
    - name: service-account
      user:
        # Use service account token
        tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
    - context:
        cluster: local
        user: service-account
