apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy
  labels:
    tier: node
    k8s-app: kube-proxy
  annotations:
    # Automatically rolls update when config changes
    checksum/config: {{ include (print $.Template.BasePath "/kube-proxy/configmap.yaml") . | sha256sum }}
spec:
  selector:
    matchLabels:
      tier: node
      k8s-app: kube-proxy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: node
        k8s-app: kube-proxy
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: kube-proxy
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      containers:
      - name: kube-proxy
        image: {{ .Values.kubeProxy.image | default (printf "k8s.gcr.io/hyperkube:v%s" .Chart.AppVersion) }}
        command:
        - ./hyperkube
        - kube-proxy
        - --config=/etc/kubernetes/kube-proxy.yaml
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10256
          initialDelaySeconds: 15
          timeoutSeconds: 15
        securityContext:
          privileged: true
        volumeMounts:
        - name: kube-proxy
          mountPath: /etc/kubernetes
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: xtables
          mountPath: /run/xtables.lock
        resources:
          requests:
            memory: 20Mi
      initContainers:
      - name: config-templates
        image: {{ .Values.kubeProxy.image | default (printf "k8s.gcr.io/hyperkube:v%s" .Chart.AppVersion) }}
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - /bin/sh
        - -c
        - |
          sed 's/HOST_IP/$(HOST_IP)/g' /etc/kubernetes.template/kube-proxy.yaml > /etc/kubernetes/kube-proxy.yaml && \
          sed -i 's/NODE_NAME/$(NODE_NAME)/g' /etc/kubernetes/kube-proxy.yaml && \
          sed 's/HOST_IP/$(HOST_IP)/g' /etc/kubernetes.template/kubeconfig > /etc/kubernetes/kubeconfig
        volumeMounts:
        - name: kube-proxy-template
          mountPath: /etc/kubernetes.template
        - name: kube-proxy
          mountPath: /etc/kubernetes
      volumes:
      - name: kube-proxy-template
        configMap:
          name: kube-proxy
      - name: kube-proxy
        emptyDir: {}
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: xtables
        hostPath:
          path: /run/xtables.lock
          type: File
